name: Pylint
on: [push, pull_request]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1

      - name: install pip packages
        run: pip install pylint requests bs4

      - name: run pylint
        shell: bash
        run: |
          cd scripts
          pylint *.py
