name: Run scripts

on:
  schedule:
    #- cron:  '0 11 * * *' # run at 13:00 ZRH time
    - cron:  '*/5 * * * *' # test...

jobs:
  parse_latest_pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: execute run-latest.sh script
      shell: bash
      run: ./run-latest.sh

    # Commit to repo with updated file
    - name: Commit and push to repo
      if: steps.changes.outputs.changed == 1 # only try to commit if there are actually changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Scraper
        commit-message: Update bag_data.csv
        rebase: 'true'

