name: Run scripts

on:
  schedule:
    - cron:  '0 * * * *' # run every hour
  workflow_dispatch: ~

jobs:
  parse_latest_pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: install poppler-utils
      run: |
        sudo apt update
        sudo apt-get install poppler-utils

    - name: install pip packages
      run: pip install bs4 requests

    - name: fetching latest daily data from BAG
      shell: bash
      run: |
        ./scripts/run-latest.sh
        ./scripts/cleanup.sh

    - name: fetching latest weekly cantonal data from BAG
      shell: bash
      run: |
        ./scripts/run-canton.sh
        ./scripts/cleanup-cantons.sh

    - name: fetching latest weekly data from BAG
      shell: bash
      run: |
        ./scripts/run-weekly.sh
        ./scripts/cleanup-weekly.sh

    # Commit to repo with updated file
    - name: Commit and push to repo
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Scraper
        commit-message: Update data from BAG
        rebase: 'true'

